name: Valist Publish

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs: 
  valist_publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: prod
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build Browser App
        run: npm run build
        env:
          NG_APP_VERSION: $(grep '"version":' package.json | cut -d\" -f4)
          NG_APP_MORALIS_API_KEY: ${{ env.NG_APP_MORALIS_API_KEY }}
          NG_APP_CERAMIC_API_HOST: ${{ env.NG_APP_CERAMIC_API_HOST }}
          NG_APP_PINATA_API_KEY: ${{ env.NG_APP_PINATA_API_KEY }}
          NG_APP_PINATA_API_SECRET: ${{ env.NG_APP_PINATA_API_SECRET }}
          NG_APP_PINATA_JWT: ${{ env.NG_APP_PINATA_JWT }}
          NG_APP_PINATA_PINNING_ENDPOINT: ${{ env.NG_APP_PINATA_PINNING_ENDPOINT }}
          NG_APP_PINATA_UNPINNING_ENDPOINT: ${{ env.NG_APP_PINATA_UNPINNING_ENDPOINT }}

      - name: Tag last-release
        shell: bash
        run: |
          CURRENT_VERSION=$(grep '"version":' package.json | cut -d\" -f4);
          git tag -f $CURRENT_VERSION;
          git push origin $CURRENT_VERSION --force

      - name: Valist Deploy
        uses: valist-io/valist-github-action@v2.5.6
        with:
          private-key: ${{ secrets.VALIST_SIGNER }}
          account: d-drive
          project: d-drive-pwa
          release: $(grep '"version":' package.json | cut -d\" -f4)
          path: dist/apps/browser